#!/usr/bin/env bash
if [[ $1 == "dev" ]]; then
	appname="Electron"
else
	appname="Cerebro"
fi

OS=$(uname -s)
echo $OS
if [[ $OS == "Darwin" ]]; then
	symlink="${HOME}/Library/Application Support/${appname}/plugins/node_modules/${PWD##*/}"
elif [[ $OS == "Linux" ]]; then
	symlink="${HOME}/.config/${appname}/plugins/node_modules/${PWD##*/}"
else
	echo "Debug only setup for linux or mac ;)"
fi

ln -s "${PWD}" "$symlink"
trap "rm \"$symlink\"" SIGHUP SIGINT SIGTERM
./node_modules/.bin/webpack --watch
